### ISSUE TITLE
Generalize Installation Instructions

### ISSUE THREAD

**Issue by MarcSkovMadsen** [AlonKellner/waloviz#10]
The current installation instruction for ffmpeg (`apt-get install ffmpeg`) can only be followed by users 1) using linux 2) having the rights to install apt-get packages. That is not always the case as users might be using other OS's or be limited in what they can install.

Please improve the installation instructions to support more users.

For example by providing alternative conda installation instructions or making seperate linux, macos and windows installation instructions.

**Comment by AlonKellner** [comment]
Hmmm that's a tricky one, even torchaudio's explanation is a bit convoluted to my taste: https://pytorch.org/audio/stable/installation.html#optional-dependencies

I can just replace the `apt-get install ffmpeg` with `conda install -c conda-forge 'ffmpeg<7'` which is better in terms of compatibility but is not native to non conda users, @MarcSkovMadsen what do you think?

**Comment by MarcSkovMadsen** [comment]
I would recommend having a Tab with `pip` and `conda` instructions seperately. With `pip` you use the current instructions, maybe explaining that `apt-get` will only work for linux users, maybe linking to windows/ macos installation instructions.

With `conda` you can install everything using `conda` I believe.

**Comment by AlonKellner** [comment]
This was solved with #13, what I ended up doing was just check if it's installed in the landing pages, if not there is a guide with conda, brew and apt-get commands, and if that fails I linked to an external multiple platform installation guide.
That seems good enough for me, I'm closing this issue :)

**Comment by MarcSkovMadsen** [comment]
Great work. Thanks.
