### ISSUE TITLE
Improve wv.extension explanation

### ISSUE THREAD

**Issue by MarcSkovMadsen** [AlonKellner/waloviz#11]
I'm a Panel user. If I was to use WaloViz it would probably be as a part of a Panel application.

Its not clear to me if `wv.extension()` is just a shorthand for `hv.extension()`?

- Can I replace or combine `wv.extension()` with `pn.extension()`?
- Can I replace or combine `wv.extension()` with `hv.extension()`?

Please document this? Thx.

**Comment by AlonKellner** [comment]
> I'm a Panel user. If I was to use WaloViz it would probably be as a part of a Panel application.
> 
> Its not clear to me if `wv.extension()` is just a shorthand for `hv.extension()`?
> 
> * Can I replace or combine `wv.extension()` with `pn.extension()`?
> * Can I replace or combine `wv.extension()` with `hv.extension()`?
> 
> Please document this? Thx.

@MarcSkovMadsen Yep that's not documented properly, the true answer is that it's a shorthand for something like:
```python
hv.extension("bokeh")
pn.extension()
```
It also has a quirky feature that makes it rerun on every single `wv.Audio` call when in Colab mode, to make it easier for users.  

Definitely will be documented later today

**Comment by AlonKellner** [comment]
This was solved with #13, both in the Getting Started guide and the API reference manual, I'm closing this issue :)

**Comment by MarcSkovMadsen** [comment]
Looks great. Thanks.
