### ISSUE TITLE
Make it clear that the widgets are actually live

### ISSUE THREAD

**Issue by MarcSkovMadsen** [AlonKellner/waloviz#12]
Maybe its just me. But coming from a HoloViz/ Panel background I'm not expecting the web page to be live.

But it seems the Audio widget out is.

I would recommend making this clearer. For example explaining this on the home age and asking the user to click it. Maybe use a more engaging wav file there too.

**Comment by AlonKellner** [comment]
@MarcSkovMadsen you're absolutely right and I will try to improve it in our landing pages, but the problem you're outlining is fundamental to the player - it does not feel interactive.  
A partial solution is proposed in #4, basically to make the cursor change.

But also changing the opacity of the spectrogram, or changing the size of the play icon or any reaction to a hover other than a toolbar fade would be better.
Not sure if even those are enough, especially on mobile devices

**Comment by MarcSkovMadsen** [comment]
If you are or know a rockstar frontend developer you could probably use an animation to make a/ the play button change size up and down a few times to signal that it can be clicked.

But just explaining that its clickable and asking the user to do it once would probably be enough.

**Comment by AlonKellner** [comment]
There are developments in #4 about the responsiveness, but the documentation was fixed in #13, I'm closing this issue :)

**Comment by MarcSkovMadsen** [comment]
I can confirm that this delivers on my feature request. Looks great.
