### ISSUE TITLE
Explain the name WaloViz

### ISSUE THREAD

**Issue by MarcSkovMadsen** [AlonKellner/waloviz#9]
Hi and congrats on the launch.

For a random visitor like me it would be really nice to have the name `WaloViz` explained on the front page of the documentation and probably also on the About page..

**Comment by AlonKellner** [comment]
@MarcSkovMadsen Thanks for the quick feedback! yeah that sounds about right, I'll add it to today's cleanup round

**Comment by AlonKellner** [comment]
This was solved with #13, closing this issue :)

**Comment by MarcSkovMadsen** [comment]
Nice explanation. Thanks.
